# Generated by Django 3.0.8 on 2020-07-07 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('show_in_menu', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('color', models.CharField(max_length=50)),
                ('keywords', models.CharField(blank=True, max_length=1000)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(null=True)),
                ('discount', models.IntegerField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand',
                                            to='shop_app.Brand')),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category',
                                   to='shop_app.Category')),
            ],
        ),
    ]
