# Generated by Django 3.0.8 on 2020-07-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop_app', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
