# Generated by Django 3.0.8 on 2020-07-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop_app', '0005_auto_20200707_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
