# Generated by Django 3.0.8 on 2020-07-07 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop_app', '0007_auto_20200707_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(
                    choices=[(1, 'XXS'), (2, 'XS'), (3, 'S'), (4, 'M'), (5, 'L'), (6, 'XL'), (7, '32'), (8, '34'),
                             (9, '36'), (10, '38'), (11, '40'), (12, '42')], max_length=200)),
                ('stock_level', models.IntegerField(default=0, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock',
                                              to='shop_app.Product')),
            ],
        ),
    ]
