# Generated by Django 3.0.8 on 2020-07-07 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop_app', '0008_stocklevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklevel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_level',
                                    to='shop_app.Product'),
        ),
    ]
