# Generated by Django 3.0.8 on 2020-07-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop_app', '0009_auto_20200707_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklevel',
            name='size',
            field=models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS')], max_length=200),
        ),
    ]
