# Generated by Django 3.0.8 on 2020-07-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop_app', '0012_auto_20200707_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklevel',
            name='size',
            field=models.CharField(
                choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('32', '32'),
                         ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42')], max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('product', 'size')},
        ),
    ]
